// src/components/BeeminderSettings.svelte
<script lang="ts">
	import { getMe, updateMe } from '@taskratchet/sdk';
	import { onMount } from 'svelte';
	const beeminderAuthUrl =
		`https://www.beeminder.com/apps/authorize?client_id=${import.meta.env.PUBLIC_BEEMINDER_CLIENT_ID}` +
		`&redirect_uri=${encodeURIComponent(import.meta.env.PUBLIC_BEEMINDER_REDIRECT_URI)}&response_type=token`;

	let bmUser = '';
	let bmGoal = '';
	let error = '';

	onMount(async () => {
		const me = await getMe();
		bmUser = me?.integrations?.beeminder?.user || '';
		bmGoal = me?.integrations?.beeminder?.goal_new_tasks || '';
	});

	async function onSubmit(event: Event) {
		event.preventDefault();
		if (!/^[-\w]*$/.test(bmGoal)) {
			error = 'Goal names can only contain letters, numbers, underscores, and hyphens.';
			return;
		}
		try {
			await updateMe({
				beeminder_goal_new_tasks: bmGoal,
			});
			error = '';
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to update settings';
		}
	}
</script>

{#if error}
	<div class="error">{error}</div>
{/if}

{#if bmUser}
	<form on:submit={onSubmit}>
		<p>Beeminder user: {bmUser}</p>

		<label>
			Post new tasks to goal:
			<input type="text" bind:value={bmGoal} />
		</label>

		<button type="submit">Save</button>
	</form>
{:else}
	<a href={beeminderAuthUrl} class="button">Enable Beeminder integration</a>
{/if}

<style>
	.error {
		color: red;
		margin-bottom: 1rem;
	}

	form {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	label {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	input {
		background: var(--background);
		color: var(--color);
		border: 1px solid var(--color);
		padding: 0.5rem;
		border-radius: 4px;
	}

	button, .button {
		align-self: flex-start;
		background: var(--background);
		color: var(--color);
		border: 1px solid var(--color);
		padding: 0.5rem 1rem;
		border-radius: 4px;
		cursor: pointer;
		text-decoration: none;
	}

	button:hover, .button:hover {
		background: var(--primary);
		border-color: var(--primary);
		color: white;
	}
</style>

// src/components/organisms/BeeminderSettings.tsx
import { LoadingButton } from '@mui/lab';
import { Alert, Button, Stack, TextField } from '@mui/material';
import type { User } from '@taskratchet/sdk';
import { type FormEvent, useEffect, useState } from 'react';

import { useMe } from '../../lib/api/useMe';
import useUpdateMe from '../../lib/api/useUpdateMe';
import * as browser from '../../lib/browser';
import { IS_PRODUCTION } from '../../tr_constants';

const beeminderClientId: string = IS_PRODUCTION
		? '1w70sy12t1106s9ptod11ex21'
		: '29k46vimhtdeptt616tuhmp2r',
	beeminderRedirect: string = IS_PRODUCTION
		? 'https://app.taskratchet.com/settings'
		: 'https://staging.taskratchet.com/settings',
	beeminderAuthUrl: string =
		`https://www.beeminder.com/apps/authorize?client_id=${beeminderClientId}` +
		`&redirect_uri=${encodeURIComponent(
			beeminderRedirect,
		)}&response_type=token`;

const BeeminderSettings = (): JSX.Element => {
	const [validationError, setValidationError] = useState<string>('');
	const me = useMe({
		refetchOnWindowFocus: false,
		onSuccess: (data: User) => {
			// TODO: Make sure this doesn't result in field being populated after initial page load
			if (bmGoal) return;
			const goal = data?.integrations?.beeminder?.goal_new_tasks ?? '';
			setBmGoal(goal);
		},
	});
	const { mutate, ...updateMe } = useUpdateMe();
	const bmUser: string = me.data?.integrations?.beeminder?.user || '';
	const [bmGoal, setBmGoal] = useState<string>('');

	useEffect(() => {
		setValidationError(
			/^[-\w]*$/.test(bmGoal)
				? ''
				: 'Goal names can only contain letters, numbers, underscores, and hyphens.',
		);
	}, [bmGoal]);

	useEffect(() => {
		const { username, access_token } = browser.getUrlParams();

		if (typeof username !== 'string' || typeof access_token !== 'string') {
			return;
		}

		mutate({
			beeminder_user: username,
			beeminder_token: access_token,
		});
	}, [mutate]);

	const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
		e.preventDefault();

		if (validationError) return;

		mutate({
			beeminder_goal_new_tasks: bmGoal,
		});
	};

	return (
		<>
			{me.error instanceof Error && (
				<Alert severity="error">{me.error.message}</Alert>
			)}
			{updateMe.error instanceof Error && (
				<Alert severity="error">{updateMe.error.message}</Alert>
			)}
			{bmUser ? (
				<form onSubmit={handleSubmit}>
					<Stack spacing={2} alignItems={'start'}>
						<p>Beeminder user: {bmUser}</p>

						<TextField
							label={'Post new tasks to goal:'}
							value={bmGoal}
							error={!!validationError}
							helperText={validationError}
							onChange={(e) => {
								setBmGoal(e.target.value);
							}}
						/>

						<LoadingButton loading={updateMe.isLoading} type="submit">
							Save
						</LoadingButton>
					</Stack>
				</form>
			) : (
				<Button href={beeminderAuthUrl} variant="outlined">
					Enable Beeminder integration
				</Button>
			)}
		</>
	);
};

export default BeeminderSettings;
